### ISSUE TITLE
[Cucumber] NoClassDefFoundError: org/junit/runner/Result

### ISSUE THREAD

**Issue by duyluonganh** [katalon-studio/katalon-studio#291]
#### Steps to reproduce:
- Run a test case with **CucumberKW.runWithFeatureFile** keyword

Expected result: KS can launch the test normally.
Actual result: KS will throw an exception:
```
Reason:
com.kms.katalon.core.exception.StepFailedException: Keyword runFeatureFile was failed (Root cause: java.lang.NoClassDefFoundError: org/junit/runner/Result
```

Related issue: https://forum.katalon.com/t/noclassdeffounderror-org-junit-runner-result/40669
https://forum.katalon.com/t/kse-7-2-5-throw-description-resource-path-location-type-groovy-unable-to-resolve-class-junit-framework-assert-workflow-groovy/40631

**Comment by cameronsampson** [comment]
I am likewise getting the same issue after upgrading from 7.2.1 to 7.2.6.

**Comment by duyluonganh** [comment]
@cameronsampson This issue has been fixed in v7.2.7. Please download it at the **release** tab.
